-----数据库用户名待确认----
--数据库,zxdb
--交易数据源:PP
--查询数据源:PPQUERY
--历史数据源:PPHIS
-------------------------------------支付请求表,主表------------------------------------------------
CREATE TABLE
    PP.TBL_PAYMENT_REQUEST(
      ID	BIGINT 	NOT NULL GENERATED ALWAYS AS IDENTITY,
      CUSTOMER_NO VARCHAR(50) NOT NULL ,
      CUSTOMER_NAME VARCHAR(100) ,
      OUT_TRADE_NO VARCHAR(60) NOT NULL ,
      ORDER_NO VARCHAR(60) NOT NULL ,
      DEAL_UNIQUE_SERIAL_NO VARCHAR(60) NOT NULL ,
      RECORD_NO VARCHAR(60) ,
      ORDER_SYSTEM VARCHAR(20) NOT NULL ,
      AMOUNT DECIMAL(15,4) NOT NULL ,
      CREATE_TIME TIMESTAMP NOT NULL ,
      PAY_STATUS VARCHAR(20) ,
      ORDER_SYSTEM_STATUS VARCHAR(20) ,
      UPDATE_TIME TIMESTAMP ,
      CONFIRM_TIME TIMESTAMP ,
      PAY_TYPE VARCHAR(20) ,
      EXPIRE_DATE TIMESTAMP ,
      CONSTRAINT TBL_PAYMENT_REQUEST PRIMARY KEY (ID),
      CONSTRAINT TBL_PAYMENT_REQUEST_UK UNIQUE (ORDER_SYSTEM,ORDER_NO)
);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_CREATE_TIME ON PP.TBL_PAYMENT_REQUEST(CREATE_TIME);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_UPDATE_TIME ON PP.TBL_PAYMENT_REQUEST(UPDATE_TIME);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_CONFIRM_TIME ON PP.TBL_PAYMENT_REQUEST(CONFIRM_TIME);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_OUT_TRADE_NO ON PP.TBL_PAYMENT_REQUEST(OUT_TRADE_NO);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_REQUEST_SYS_ID ON PP.TBL_PAYMENT_REQUEST(CONFIRM_TIME);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_DEAL_UNIQUE_SERIAL_NO ON PP.TBL_PAYMENT_REQUEST(DEAL_UNIQUE_SERIAL_NO);
CREATE INDEX PP.TBL_PAYMENT_REQUEST_RECORD_NO ON PP.TBL_PAYMENT_REQUEST(RECORD_NO);
CREATE UNIQUE INDEX PP.TBL_PAYMENT_REQUEST_ORDER_NO ON PP.TBL_PAYMENT_REQUEST (ORDER_NO, ORDER_SYSTEM);

GRANT SELECT,INSERT,UPDATE,DELETE ON PP.TBL_PAYMENT_REQUEST TO USER PPAPP;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_REQUEST  TO USER PNCASH;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_REQUEST  TO USER OPENQ;

-------------------------------------支付记录表,子表------------------------------------------------
CREATE TABLE
    PP.TBL_PAYMENT_PAY_RECORD(
      REQUEST_ID	BIGINT	NOT NULL ,
      RECORD_NO	VARCHAR(60) NOT NULL,
      BANK_ORDER_NO	VARCHAR(60),
      BANK_SEQ	VARCHAR(60),
      BANK_TRX_ID	VARCHAR(100),
      PAYMENT_NO	VARCHAR(60),
      PLATFORM_TYPE	VARCHAR(20),
      PAY_ORDER_TYPE VARCHAR(20),
      STATUS	VARCHAR(20),
      AMOUNT	DECIMAL(15,4),
      COST	DECIMAL(15,4),
      USER_FEE	DECIMAL(15,4),
      SMS_TYPE	VARCHAR(50),
      CREATE_TIME	TIMESTAMP	,
      UPDATE_TIME	TIMESTAMP	,
      PAY_TIME	TIMESTAMP	,
      BANK_ID VARCHAR(20),
      BIND_CARD_ID VARCHAR(60),
      FRP_CODE VARCHAR(60),
      CARD_TYPE VARCHAR(30),
      CARD_ID VARCHAR(60),
      CASHIER_VERSION VARCHAR(30),
      PAY_PRODUCT VARCHAR(30),
      PAY_SCENE VARCHAR(30),
      PAYER_IP VARCHAR(20),
      ERROR_CODE VARCHAR(50),
      ERROR_MSG VARCHAR(255),
      REQUEST_SYSTEM VARCHAR(20),
      REQUEST_SYS_ID VARCHAR(60),
      BANK_ACCOUNT_TYPE VARCHAR(20),
      CONSTRAINT TBL_PAYMENT_REQUEST PRIMARY KEY (RECORD_NO),
      CONSTRAINT TBL_PAYMENT_REQUEST_UK UNIQUE (RECORD_NO)
);

CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_CREATE_TIME ON PP.TBL_PAYMENT_PAY_RECORD(CREATE_TIME);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_PAY_TIME ON PP.TBL_PAYMENT_PAY_RECORD(PAY_TIME);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_BANK_ORDER_NO ON PP.TBL_PAYMENT_PAY_RECORD(BANK_ORDER_NO);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_REQUEST_ID ON PP.TBL_PAYMENT_PAY_RECORD(REQUEST_ID);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_BANK_TRX_ID ON PP.TBL_PAYMENT_PAY_RECORD(BANK_TRX_ID);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_PAYMENT_NO ON PP.TBL_PAYMENT_PAY_RECORD(PAYMENT_NO);
CREATE INDEX PP.TBL_PAYMENT_PAY_RECORD_BANK_SEQ ON PP.TBL_PAYMENT_PAY_RECORD(BANK_SEQ);

GRANT SELECT,INSERT,UPDATE,DELETE ON PP.TBL_PAYMENT_PAY_RECORD TO USER PPAPP;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_PAY_RECORD  TO USER PNCASH;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_PAY_RECORD  TO USER OPENQ;

-------------------------------------退款记录表------------------------------------------------
CREATE TABLE
    PP.TBL_PAYMENT_REVERSE_RECORD(
      ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      REQUEST_ID	BIGINT NOT NULL,
      RECORD_NO	VARCHAR(60) NOT NULL,
      REFUND_STATUS	VARCHAR(20),
      REQUEST_TIME	TIMESTAMP	,
      MODIFY_TIME	TIMESTAMP	,
      SUCCESS_TIME	TIMESTAMP	,
      REMARK	VARCHAR(256),
      CONSTRAINT TBL_PAYMENT_REVERSE_RECORD PRIMARY KEY (ID),
      CONSTRAINT TBL_PAYMENT_REVERSE_RECORD_UK UNIQUE (RECORD_NO)
);

CREATE INDEX PP.TBL_PAYMENT_REVERSE_RECORD_REQUEST_TIME ON PP.TBL_PAYMENT_REVERSE_RECORD(REQUEST_TIME);
CREATE INDEX PP.TBL_PAYMENT_REVERSE_RECORD_MODIFY_TIME ON PP.TBL_PAYMENT_REVERSE_RECORD(MODIFY_TIME);
CREATE INDEX PP.TBL_PAYMENT_REVERSE_RECORD_SUCCESS_TIME ON PP.TBL_PAYMENT_REVERSE_RECORD(SUCCESS_TIME);
CREATE INDEX PP.TBL_PAYMENT_REVERSE_RECORD_RECORD_NO ON PP.TBL_PAYMENT_REVERSE_RECORD(RECORD_NO);

GRANT SELECT,INSERT,UPDATE,DELETE ON PP.TBL_PAYMENT_REVERSE_RECORD TO USER PP;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_REVERSE_RECORD  TO USER PNCASH;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_REVERSE_RECORD  TO USER OPENQ;


------------------预授权"退款"记录-------------------------
CREATE TABLE
    PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD(
      ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
      REQUEST_ID	BIGINT NOT NULL,
      RECORD_NO	VARCHAR(60) NOT NULL,
      PAYMENT_NO VARCHAR(60),
      ORG_PAY_ORDER_TYPE VARCHAR (60),
      PAY_ORDER_TYPE VARCHAR (20),
      CANCEL_STATUS	VARCHAR(20),
      REQUEST_TIME	TIMESTAMP	,
      MODIFY_TIME	TIMESTAMP	,
      SUCCESS_TIME	TIMESTAMP	,
      REMARK	VARCHAR(256),
      CONSTRAINT TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD PRIMARY KEY (ID),
      CONSTRAINT TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD_UK UNIQUE (RECORD_NO)
);
CREATE INDEX PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD_REQUEST_TIME ON PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD(REQUEST_TIME);
CREATE INDEX PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD_MODIFY_TIME ON PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD(MODIFY_TIME);
CREATE INDEX PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD_SUCCESS_TIME ON PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD(SUCCESS_TIME);
CREATE INDEX PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD_RECORD_NO ON PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD(RECORD_NO);

GRANT SELECT,INSERT,UPDATE,DELETE ON PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD TO USER PPAPP;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD  TO USER PNCASH;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_PRE_AUTH_REVERSE_RECORD  TO USER DBVIEWER;




----------添加表格和添加字段------------

----------创建表格PP.TBL_PAYMENT_COMB_PAY_RECORD----------------------
----------分区字段：按创建时间CREATE_TIME做分区-------
CREATE TABLE
    PP.TBL_PAYMENT_COMB_PAY_RECORD
    (
        ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        RECORD_NO VARCHAR(64) NOT NULL,
        PAY_ORDER_TYPE VARCHAR(32),
        MARKETING_NO VARCHAR(64),
        PAY_ORDER_NO VARCHAR(64),
        BANK_ORDER_NO VARCHAR(64),
        AMOUNT DECIMAL(15,4),
        STATUS VARCHAR(32),
        PAY_PRODUCT VARCHAR(32),
        CREATE_TIME TIMESTAMP NOT NULL,
        UPDATE_TIME TIMESTAMP,
        PAY_TIME TIMESTAMP,
        FRP_CODE VARCHAR(64),
        ERROR_CODE VARCHAR(64),
        ERROR_MSG VARCHAR(256),
        CONSTRAINT TBL_PAYMENT_COMB_PAY_RECORD_PK PRIMARY KEY (ID)
    );

CREATE INDEX PP.TBL_PAYMENT_COMB_PAY_RECORD_CREATE_TIME ON PP.TBL_PAYMENT_COMB_PAY_RECORD(CREATE_TIME);
CREATE INDEX PP.TBL_PAYMENT_COMB_PAY_RECORD_UPDATE_TIME ON PP.TBL_PAYMENT_COMB_PAY_RECORD(UPDATE_TIME);
CREATE UNIQUE INDEX PP.TBL_PAYMENT_COMB_PAY_RECORD_RECORD_NO ON PP.TBL_PAYMENT_COMB_PAY_RECORD(RECORD_NO);

GRANT SELECT,INSERT,UPDATE,DELETE ON PP.TBL_PAYMENT_COMB_PAY_RECORD TO USER PPAPP;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_COMB_PAY_RECORD  TO USER PNCASH;
GRANT SELECT ON TABLE PP.TBL_PAYMENT_COMB_PAY_RECORD  TO USER DBVIEWER;


ALTER TABLE pp.TBL_PAYMENT_PAY_RECORD ADD COLUMN FIRST_PAY_AMOUNT DECIMAL(15,4);
ALTER TABLE pp.TBL_PAYMENT_PAY_RECORD ADD COLUMN COMBINED_PAY VARCHAR(1);


