/*==============================================================*/
/* Table: TBL_NCCA_PAY_REQ      支付请求                                */
/*==============================================================*/
create table TBL_NCCA_PAY_REQ 
(
   ID                   bigint                         not null generated by default as identity
      (
          start with 1,
          increment by 1,
        minvalue 1
      ),
   TRADE_SYS_ORDER_ID   varchar(32)                    not null,
   TRADE_SYS_NO         varchar(32)                    not null,
   BIZ_MODE_CODE        varchar(32)                    not null,
   MERCHANT_NO          varchar(32)                    not null,
   MERCHANT_ORDER_ID    varchar(64)                    not null,
   MERCHANT_NAME        varchar(64)                    null,
   PRODUCT_NAME         varchar(64)                    null,
   CASHIER_VERSION      varchar(16)                    null,
   THEME_CUSTOM_CODE    varchar(16)                    null,
   ORDER_AMOUNT         decimal(10,2)                  null,
   COST                 decimal(10,2)                  null,
   PAY_METHOD           varchar(16)                    null,
   USER_UA              varchar(300)                   null,
   USER_IP              varchar(16)                    null,
   BIND_ID              varchar(20)                    null,
   CARD_INFO_ID         varchar(20)                    null,
   CARD_NO              varchar(64)                    null,
   CARD_TYPE            varchar(16)                    null,
   BANK_CODE            varchar(16)                    null,
   PAYMENT_ORDER_NO     varchar(36)                    null,
   PAYMENT_SYS_NO       varchar(36)                    null,
   ORDER_EXP_DATE       int                            null,
   ERROR_CODE           varchar(16)                    null,
   ERROR_MSG            varchar(300)                   null,
   STATE                varchar(16)                    null,
   INDUSTRY_CATALOG     varchar(32)                    null,
   IDENTITY_ID          varchar(36)                    null,
   IDENTITY_TYPE        varchar(36)                    null,
   OWNER                varchar(100)                   null,
   ID_CARD_TYPE         varchar(16)                    null,
   ID_CARD              varchar(64)                    null,
   PHONE_NO             varchar(64)                    null,
   CURRENCY             varchar(16)                    null,
   AREA_INFO            varchar(64)                    null,
   TRADE_RISK_INFO      varchar(200)                   null,
   QUERY_RISK_INFO      varchar(300)                   null,
   MERCHANT_ORDER_URL   varchar(200)                   null,
   FRONT_CALL_BACK_URL  varchar(200)                   null,
   PAY_TIME             timestamp                      null,
   TERMINAL_INFO        varchar(300)                   null,
   APP_INFO             varchar(300)                   null,
   CREATE_TIME          timestamp                      null,
   UPDATE_TIME          timestamp                      null,
   VERSION              int                            null,
   REMARK               varchar(128)                   null, 
   constraint PK_PAY_REQ primary key (ID)
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REQ_1                                    */
/*==============================================================*/
create unique index IND_NCCA_PAY_REQ_1 on TBL_NCCA_PAY_REQ (
TRADE_SYS_ORDER_ID ASC,
TRADE_SYS_NO ASC
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REQ_2                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REQ_2 on TBL_NCCA_PAY_REQ (
MERCHANT_NO ASC,
MERCHANT_ORDER_ID ASC
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REQ_3                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REQ_3 on TBL_NCCA_PAY_REQ (
CREATE_TIME ASC
);


/*==============================================================*/
/* Table: TBL_NCCA_PAY_REC    支付请求记录                                  */
/*==============================================================*/
create table TBL_NCCA_PAY_REC 
(
   ID                   bigint                         not null  generated by default as identity
      (
          start with 1,
          increment by 1,
        minvalue 1
      ),
   PAYMENT_REQUEST_ID   bigint                         null,
   TRADE_SYS_ORDER_ID   varchar(32)                    null,
   TRADE_SYS_NO         varchar(32)                    null,
   BIZ_MODE_CODE        varchar(32)                    null,
   TOKEN_ID             varchar(64)                    null,
   PAYMENT_AMOUNT       decimal(10,2)                  null,
   COST                 decimal(10,2)                  null,
   PAYMENT_SYS_NO       varchar(32)                    null,
   PAYMENT_ORDER_NO     varchar(32)                    null,
   PAY_PRODUCT_CODE     varchar(16)                    null,
   BANK_ORDER_NO        varchar(32)                    null,
   BANK_CHANNEL_NO      varchar(64)                    null,
   MERCHANT_NO          varchar(32)                    null,
   MERCHANT_NAME        varchar(64)                    null,
   MERCHANT_ORDER_ID    varchar(64)                    null,
   PRODUCT_NAME         varchar(64)                    null,
   PAY_TYPE             varchar(16)                    null,
   TRADE_RISK_INFO      varchar(300)                   null,
   AREA_INFO            varchar(64)                    null,
   MCC                  varchar(32)                    null,
   SMS_VERIFY_TYPE      varchar(16)                    null,
   BIND_ID              varchar(20)                    null,
   CARD_INFO_ID         varchar(20)                    null,
   OWNER                varchar(100)                   null,
   CARD_TYPE            varchar(16)                    null,
   BANK_CODE            varchar(16)                    null,
   CARD_NO              varchar(64)                    null,
   ID_CARD_TYPE         varchar(16)                    null,
   PHONE_NO             varchar(64)                    null,
   ID_CARD              varchar(64)                    null,
   VERIFY_CODE          varchar(8)                     null,
   MEMBER_NO            varchar(32)                    null,
   MEMBER_TYPE          varchar(16)                    null,
   ERROR_CODE           varchar(16)                    null,
   ERROR_MSG            varchar(300)                   null,
   STATE                varchar(16)                    null,
   CREATE_TIME          timestamp                      null,
   UPDATE_TIME          timestamp                      null,
   VERSION              int                            null,
   REMARK               varchar(128)                   null,
   constraint PK_PAY_REC primary key (ID)
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REC_1                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REC_1 on TBL_NCCA_PAY_REC (
TRADE_SYS_ORDER_ID ASC,
TRADE_SYS_NO ASC
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REC_2                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REC_2 on TBL_NCCA_PAY_REC (
MERCHANT_NO ASC,
MERCHANT_ORDER_ID ASC
);

/*==============================================================*/
/* Index: IND_NCCA_PAY_REC_3                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REC_3 on TBL_NCCA_PAY_REC (
CREATE_TIME ASC
);
/*==============================================================*/
/* Index: IND_NCCA_PAY_REC_4                                    */
/*==============================================================*/
create index IND_NCCA_PAY_REC_4 on TBL_NCCA_PAY_REC (
PAYMENT_ORDER_NO ASC,
PAYMENT_SYS_NO ASC
);
/**
 * Index: IND_NCCA_PAY_REC_5
 */
create index IND_NCCA_PAY_REC_5 on TBL_NCCA_PAY_REC (TOKEN_ID ASC);
/*==============================================================*/
/* Table: TBL_NCCA_USER_ACC           用户访问信息                          */
/*==============================================================*/
create table TBL_NCCA_USER_ACC 
(
   ID                   bigint                         not null  generated by default as identity
      (
          start with 1,
          increment by 1,
        minvalue 1
      ),
   PAYMENT_REQUEST_ID   bigint                         null,
   TOKEN_ID             varchar(64)                    null,
   MERCHANT_NO          varchar(32)                    null,
   TRADE_SYS_ORDER_ID   varchar(32)                    null,
   TRADE_SYS_NO         varchar(32)                    null,
   USER_IP              varchar(16)                    null,
   USER_UA              varchar(300)                   null,
   PARAM_SHOW_INFO      varchar(3000)                   null,
   constraint PK_USER_ACC primary key (ID)
);

/*==============================================================*/
/* Index: IND_NCCA_USER_ACC_1                                    */
/*==============================================================*/
create index IND_NCCA_USER_ACC_1 on TBL_NCCA_USER_ACC (TOKEN_ID ASC);

/*==============================================================*/
/* Table: TBL_NCCA_BEHA_ANAL     行为分析                               */
/*==============================================================*/
create table TBL_NCCA_BEHA_ANAL 
(
   ID                   bigint                         not null   generated by default as identity
      (
          start with 1,
          increment by 1,
        minvalue 1
      ),
   TOKEN_ID             varchar(64)                    null,
   URL                  varchar(200)                   null,
   SERVER_DEC           varchar(200)                   null,
   ENTER_TIME           timestamp                      null,
   LEAVE_TIME           timestamp                      null,
   LAST_URL             varchar(200)                   null,
   CREATE_TIME          timestamp                      null,
   UPDATE_TIME          timestamp                      null,
   constraint PK_BEHA_ANAL primary key (ID)
);


/*==============================================================*/
/* Table: TBL_NCCA_THEME_SET           主题扩展                         */
/*==============================================================*/
create table TBL_NCCA_THEME_SET 
(
   ID                   bigint                         not null  generated by default as identity
      (
          start with 1,
          increment by 1,
        minvalue 1
      ),
   THEME_SETTING_CODE   varchar(16)                    null,
   THEME_STYLE_CONFIG   varchar(32)                    null,
   BUSIN_CODE           varchar(32)                    null,
   MERCHANT_NO          varchar(16)                    null,
   COMPON_CONFIG        varchar(20)                    null,
   CREATE_TIME          timestamp                      null,
   UPDATE_TIME          timestamp                      null,
   constraint PK_THEME_SET primary key (ID)
);